Fixed shooting while reloading
anderbellstudios/pop-pixie pull request #2
Opened 2023-07-06 20:54 UTC by timmiedinnie

- Fixed that you cannot shoot while reloading
- isolated some methods and made some imrpovements for readability and reusability

2023-07-06 20:56 UTC, timmiedinnie commented
**Before**
![before](https://github.com/anderbellstudios/pop-pixie/assets/3026022/bb0fca4a-e8cd-4a70-94f1-3eab10064512)
**After:**
![after](https://github.com/anderbellstudios/pop-pixie/assets/3026022/c1eff06f-8658-4e95-bac9-0443484fe330)

2023-07-06 22:11 UTC, 12joan requested changes
I'm glad to see you were able to get Pop Pixie running.

In future, can you ask us on Discord before making any changes to the gameplay? As it happens, our team has talked about this particular change in the past, so I'm willing to give it a trial run to see how it plays.

I've left a few notes in the review comments. In addition, I noticed that `WeaponReload.cs` has an inconsistent mix of tabs and spaces that shows up on GitHub (an old issue from the code's early days). Would you mind fixing those since you're already editing the file? 🙂

2023-07-06 22:11 UTC, 12joan commented on Assets/src/PlayerWeapons.cs
> +  public bool isReloading = false;
We use PascalCase for class fields. It's probably not what most C# projects are using nowadays, but best to keep it consistent.

2023-07-06 22:11 UTC, 12joan commented on Assets/src/WeaponReload.cs
> +  private const float movementSpeedReduction = 0.5f;
Same here with regard to PascalCase

2023-07-06 22:11 UTC, 12joan commented on Assets/src/WeaponReload.cs
> +  private void InitializeReloadTimer() {
There's probably not much point in putting this in its own function if it's the only thing called from Start. Can we revert this?

2023-07-06 22:11 UTC, 12joan commented on Assets/src/WeaponReload.cs
> +    ReloadTimer = new IntervalTimer(){TimeClass = "PlayingTime"};
```suggestion
    ReloadTimer = new IntervalTimer() {
      TimeClass = "PlayingTime"
    };

```

2023-07-06 22:11 UTC, 12joan commented on Assets/src/WeaponReload.cs
> +  }
There seems to be some unintended duplication here? It's a little hard to make sense of what's going on with these changes.

2023-07-06 22:11 UTC, 12joan commented on Assets/src/WeaponReload.cs
> +  }
Can you make sure to add an empty line between each method definition?

2023-07-06 22:11 UTC, 12joan commented on Assets/src/PlayerWeapons.cs
> +  public bool isReloading = false;
Actually, on second thought, would it be possible to remove `isReloading` and use the existing `WeaponReload.InProgress()`  method instead?

2023-09-17 16:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/anderbellstudios/pop-pixie?pullRequest=2) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/anderbellstudios/pop-pixie?pullRequest=2) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/anderbellstudios/pop-pixie?pullRequest=2) it.</sub>

2024-01-17 20:32 UTC, closed without merging